mysql:
  host: "localhost"
  user: "root"
  password: "rootpassword"
  database: "my_analytics_db"

redis:
  host: "localhost"
  port: 6379
  db: 0

app:
  environment: "development"
  log_level: "INFO"
